# https://github.com/pajikos/home-assistant-helm-chart/blob/main/charts/home-assistant/values.yaml

image:
  # https://github.com/home-assistant/core/releases
  # https://github.com/home-assistant/core/pkgs/container/home-assistant
  repository: "ghcr.io/home-assistant/home-assistant"
  tag: "2025.12.4"
env:
- name: "TZ"
  value: "Europe/Zurich"
nodeSelector:
  device: zigbee-hub
# Required for use auto-discovery feature of Home Assistant
hostNetwork: true
hostPort:
  enabled: true # can be enabled once ingress is enabled
  port: 8123
ingress:
  # Enable ingress for home assistant
  enabled: false # TODO
persistence:
  enabled: true
  size: 1
  storageClass: "local-path-btrfs"
additionalVolumes:
- name: zigbee-hub
  hostPath:
    type: CharDevice
    path: "/dev/serial/by-id/usb-ITEAD_SONOFF_Zigbee_3.0_USB_Dongle_Plus_V2_20231008100925-if00"
additionalMounts:
- name: zigbee-hub
  mountPath: "/dev/ttyACM0"
securityContext:
  privileged: true # required to mount a device
