grafana:
    adminUser: ENC[AES256_GCM,data:gtxtusg=,iv:+LqB3wFTg+fZnNu/jr18PBJWG+AGo5r6MJ2sR7wd1oY=,tag:J7ArD7iArm0qMQaH271z+Q==,type:str]
    adminPassword: ENC[AES256_GCM,data:1jJbSY8dDDYZudSSpB+rJA/5FtoDzKTWhPUhr+mBLw==,iv:p7KNwCsHAk5uFJblT0vrKB4kJ3TltyHhhoBE1u+UkBw=,tag:bPNAgCZ+lUg791FK2/P2Tg==,type:str]
sops:
    age:
        - recipient: age1lk9rqgq9kls8u08vadgc8pq2vwamrjkgzn3ekvthlmfffh4akflsauata6
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBhUFUxTjViTXFjUDZranh1
            SC9hSWQ5dTZ3L2RjSmxaZE5HSHllM3REajFzCmNKcTNBQUV0VS9zTk0xaGxBK0pu
            RFZDemFORHlPODNxMHJUMnd2aGgxRDQKLS0tIHNMeWhXR25QSHUwQlBSdTRiQ05j
            a1p6c0RGTTAweEhGeHlYRnFBNzlKMTAKvpYg7dDqMg9Pu/tooXGibRnRTxkqifWI
            v3CoUNrOL9dgJnCV1+8dIq5N8BsOGILG1NngI1Z+ejVX0CBZ+6Fcnw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-11-19T17:22:20Z"
    mac: ENC[AES256_GCM,data:jeiRyorHw2EiiirjkwVzQwJ/A0MuEm0ylSff0xFaDstGakzgDAC9mVKRipQmG/sAHHJDbpUmPsk+W5tnIJIN5oZDFqQsMu15sxcbdmCbuZcdFik79PhvZvjaEE+Zev9smHv9YVniRUubewD0h2IHVHNGgLO0BkfwUtuNuPhNVVA=,iv:pUTy4LfSG/OCeW1SbxxEybj7sgONZHGBGEmmN7NdnXA=,tag:tHjlnLALJg63sGbTEdiGMQ==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.10.2
